//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KtvStudio.RoomTaskService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomTask", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class RoomTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomConsumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomConsume {
            get {
                return this.RoomConsumeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomConsumeField, value) != true)) {
                    this.RoomConsumeField = value;
                    this.RaisePropertyChanged("RoomConsume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomIdField, value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomState {
            get {
                return this.RoomStateField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomStateField, value) != true)) {
                    this.RoomStateField = value;
                    this.RaisePropertyChanged("RoomState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class CustomerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAge {
            get {
                return this.CustomerAgeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAgeField, value) != true)) {
                    this.CustomerAgeField = value;
                    this.RaisePropertyChanged("CustomerAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerIdCard {
            get {
                return this.CustomerIdCardField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdCardField, value) != true)) {
                    this.CustomerIdCardField = value;
                    this.RaisePropertyChanged("CustomerIdCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSex {
            get {
                return this.CustomerSexField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSexField, value) != true)) {
                    this.CustomerSexField = value;
                    this.RaisePropertyChanged("CustomerSex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTel {
            get {
                return this.CustomerTelField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTelField, value) != true)) {
                    this.CustomerTelField = value;
                    this.RaisePropertyChanged("CustomerTel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomTaskService.IRoomTaskManagement")]
    public interface IRoomTaskManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetAllRoomTask", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetAllRoomTaskResponse")]
        System.Data.DataTable GetAllRoomTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetAllRoomTask", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetAllRoomTaskResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllRoomTaskAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/UpdateRoomInfo", ReplyAction="http://tempuri.org/IRoomTaskManagement/UpdateRoomInfoResponse")]
        int UpdateRoomInfo(KtvStudio.RoomTaskService.RoomTask roomTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/UpdateRoomInfo", ReplyAction="http://tempuri.org/IRoomTaskManagement/UpdateRoomInfoResponse")]
        System.Threading.Tasks.Task<int> UpdateRoomInfoAsync(KtvStudio.RoomTaskService.RoomTask roomTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetAccentRoomConsume", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetAccentRoomConsumeResponse")]
        int GetAccentRoomConsume(KtvStudio.RoomTaskService.RoomTask roomTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetAccentRoomConsume", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetAccentRoomConsumeResponse")]
        System.Threading.Tasks.Task<int> GetAccentRoomConsumeAsync(KtvStudio.RoomTaskService.RoomTask roomTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetUserInfoById", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetUserInfoByIdResponse")]
        System.Data.DataTable GetUserInfoById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetUserInfoById", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetUserInfoByIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetUserInfoByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/UpdateUserInfo", ReplyAction="http://tempuri.org/IRoomTaskManagement/UpdateUserInfoResponse")]
        int UpdateUserInfo(KtvStudio.RoomTaskService.CustomerInfo customerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/UpdateUserInfo", ReplyAction="http://tempuri.org/IRoomTaskManagement/UpdateUserInfoResponse")]
        System.Threading.Tasks.Task<int> UpdateUserInfoAsync(KtvStudio.RoomTaskService.CustomerInfo customerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/InsertUserInfo", ReplyAction="http://tempuri.org/IRoomTaskManagement/InsertUserInfoResponse")]
        int InsertUserInfo(KtvStudio.RoomTaskService.CustomerInfo customerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/InsertUserInfo", ReplyAction="http://tempuri.org/IRoomTaskManagement/InsertUserInfoResponse")]
        System.Threading.Tasks.Task<int> InsertUserInfoAsync(KtvStudio.RoomTaskService.CustomerInfo customerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/HasExistUser", ReplyAction="http://tempuri.org/IRoomTaskManagement/HasExistUserResponse")]
        int HasExistUser(string customerIdCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/HasExistUser", ReplyAction="http://tempuri.org/IRoomTaskManagement/HasExistUserResponse")]
        System.Threading.Tasks.Task<int> HasExistUserAsync(string customerIdCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetCustomerIdByIdCard", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetCustomerIdByIdCardResponse")]
        string GetCustomerIdByIdCard(string customerIdCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetCustomerIdByIdCard", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetCustomerIdByIdCardResponse")]
        System.Threading.Tasks.Task<string> GetCustomerIdByIdCardAsync(string customerIdCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/AddConsumeLog", ReplyAction="http://tempuri.org/IRoomTaskManagement/AddConsumeLogResponse")]
        int AddConsumeLog(KtvStudio.RoomTaskService.RoomTask roomTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/AddConsumeLog", ReplyAction="http://tempuri.org/IRoomTaskManagement/AddConsumeLogResponse")]
        System.Threading.Tasks.Task<int> AddConsumeLogAsync(KtvStudio.RoomTaskService.RoomTask roomTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetRoomPriceSource", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetRoomPriceSourceResponse")]
        System.Data.DataTable GetRoomPriceSource();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetRoomPriceSource", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetRoomPriceSourceResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRoomPriceSourceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetConsumeLog", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetConsumeLogResponse")]
        System.Data.DataTable GetConsumeLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTaskManagement/GetConsumeLog", ReplyAction="http://tempuri.org/IRoomTaskManagement/GetConsumeLogResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetConsumeLogAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomTaskManagementChannel : KtvStudio.RoomTaskService.IRoomTaskManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomTaskManagementClient : System.ServiceModel.ClientBase<KtvStudio.RoomTaskService.IRoomTaskManagement>, KtvStudio.RoomTaskService.IRoomTaskManagement {
        
        public RoomTaskManagementClient() {
        }
        
        public RoomTaskManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomTaskManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomTaskManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomTaskManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllRoomTask() {
            return base.Channel.GetAllRoomTask();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllRoomTaskAsync() {
            return base.Channel.GetAllRoomTaskAsync();
        }
        
        public int UpdateRoomInfo(KtvStudio.RoomTaskService.RoomTask roomTask) {
            return base.Channel.UpdateRoomInfo(roomTask);
        }
        
        public System.Threading.Tasks.Task<int> UpdateRoomInfoAsync(KtvStudio.RoomTaskService.RoomTask roomTask) {
            return base.Channel.UpdateRoomInfoAsync(roomTask);
        }
        
        public int GetAccentRoomConsume(KtvStudio.RoomTaskService.RoomTask roomTask) {
            return base.Channel.GetAccentRoomConsume(roomTask);
        }
        
        public System.Threading.Tasks.Task<int> GetAccentRoomConsumeAsync(KtvStudio.RoomTaskService.RoomTask roomTask) {
            return base.Channel.GetAccentRoomConsumeAsync(roomTask);
        }
        
        public System.Data.DataTable GetUserInfoById(string id) {
            return base.Channel.GetUserInfoById(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetUserInfoByIdAsync(string id) {
            return base.Channel.GetUserInfoByIdAsync(id);
        }
        
        public int UpdateUserInfo(KtvStudio.RoomTaskService.CustomerInfo customerInfo) {
            return base.Channel.UpdateUserInfo(customerInfo);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserInfoAsync(KtvStudio.RoomTaskService.CustomerInfo customerInfo) {
            return base.Channel.UpdateUserInfoAsync(customerInfo);
        }
        
        public int InsertUserInfo(KtvStudio.RoomTaskService.CustomerInfo customerInfo) {
            return base.Channel.InsertUserInfo(customerInfo);
        }
        
        public System.Threading.Tasks.Task<int> InsertUserInfoAsync(KtvStudio.RoomTaskService.CustomerInfo customerInfo) {
            return base.Channel.InsertUserInfoAsync(customerInfo);
        }
        
        public int HasExistUser(string customerIdCard) {
            return base.Channel.HasExistUser(customerIdCard);
        }
        
        public System.Threading.Tasks.Task<int> HasExistUserAsync(string customerIdCard) {
            return base.Channel.HasExistUserAsync(customerIdCard);
        }
        
        public string GetCustomerIdByIdCard(string customerIdCard) {
            return base.Channel.GetCustomerIdByIdCard(customerIdCard);
        }
        
        public System.Threading.Tasks.Task<string> GetCustomerIdByIdCardAsync(string customerIdCard) {
            return base.Channel.GetCustomerIdByIdCardAsync(customerIdCard);
        }
        
        public int AddConsumeLog(KtvStudio.RoomTaskService.RoomTask roomTask) {
            return base.Channel.AddConsumeLog(roomTask);
        }
        
        public System.Threading.Tasks.Task<int> AddConsumeLogAsync(KtvStudio.RoomTaskService.RoomTask roomTask) {
            return base.Channel.AddConsumeLogAsync(roomTask);
        }
        
        public System.Data.DataTable GetRoomPriceSource() {
            return base.Channel.GetRoomPriceSource();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRoomPriceSourceAsync() {
            return base.Channel.GetRoomPriceSourceAsync();
        }
        
        public System.Data.DataTable GetConsumeLog() {
            return base.Channel.GetConsumeLog();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetConsumeLogAsync() {
            return base.Channel.GetConsumeLogAsync();
        }
    }
}
