//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KtvStudio.RoomInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomInfo", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class RoomInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AirConditionerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EffectorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LCDTVNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MicroPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PowerAmplifierNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SongDeskNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoundNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AirConditionerNumber {
            get {
                return this.AirConditionerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AirConditionerNumberField, value) != true)) {
                    this.AirConditionerNumberField = value;
                    this.RaisePropertyChanged("AirConditionerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EffectorNumber {
            get {
                return this.EffectorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EffectorNumberField, value) != true)) {
                    this.EffectorNumberField = value;
                    this.RaisePropertyChanged("EffectorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LCDTVNumber {
            get {
                return this.LCDTVNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LCDTVNumberField, value) != true)) {
                    this.LCDTVNumberField = value;
                    this.RaisePropertyChanged("LCDTVNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MicroPhoneNumber {
            get {
                return this.MicroPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MicroPhoneNumberField, value) != true)) {
                    this.MicroPhoneNumberField = value;
                    this.RaisePropertyChanged("MicroPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerAmplifierNumber {
            get {
                return this.PowerAmplifierNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PowerAmplifierNumberField, value) != true)) {
                    this.PowerAmplifierNumberField = value;
                    this.RaisePropertyChanged("PowerAmplifierNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomIdField, value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomRemark {
            get {
                return this.RoomRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomRemarkField, value) != true)) {
                    this.RoomRemarkField = value;
                    this.RaisePropertyChanged("RoomRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomSize {
            get {
                return this.RoomSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomSizeField, value) != true)) {
                    this.RoomSizeField = value;
                    this.RaisePropertyChanged("RoomSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomType {
            get {
                return this.RoomTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeField, value) != true)) {
                    this.RoomTypeField = value;
                    this.RaisePropertyChanged("RoomType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SongDeskNumber {
            get {
                return this.SongDeskNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SongDeskNumberField, value) != true)) {
                    this.SongDeskNumberField = value;
                    this.RaisePropertyChanged("SongDeskNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoundNumber {
            get {
                return this.SoundNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SoundNumberField, value) != true)) {
                    this.SoundNumberField = value;
                    this.RaisePropertyChanged("SoundNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomInfoService.IRoomInfoManagement")]
    public interface IRoomInfoManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/GetAllRoomInfo", ReplyAction="http://tempuri.org/IRoomInfoManagement/GetAllRoomInfoResponse")]
        System.Data.DataTable GetAllRoomInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/GetAllRoomInfo", ReplyAction="http://tempuri.org/IRoomInfoManagement/GetAllRoomInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllRoomInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/InsertRoomInfo", ReplyAction="http://tempuri.org/IRoomInfoManagement/InsertRoomInfoResponse")]
        int InsertRoomInfo(KtvStudio.RoomInfoService.RoomInfo roomInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/InsertRoomInfo", ReplyAction="http://tempuri.org/IRoomInfoManagement/InsertRoomInfoResponse")]
        System.Threading.Tasks.Task<int> InsertRoomInfoAsync(KtvStudio.RoomInfoService.RoomInfo roomInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/RemoveRoomInfo", ReplyAction="http://tempuri.org/IRoomInfoManagement/RemoveRoomInfoResponse")]
        int RemoveRoomInfo(string roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/RemoveRoomInfo", ReplyAction="http://tempuri.org/IRoomInfoManagement/RemoveRoomInfoResponse")]
        System.Threading.Tasks.Task<int> RemoveRoomInfoAsync(string roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/UpdateRoomInfo", ReplyAction="http://tempuri.org/IRoomInfoManagement/UpdateRoomInfoResponse")]
        int UpdateRoomInfo(KtvStudio.RoomInfoService.RoomInfo roomInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/UpdateRoomInfo", ReplyAction="http://tempuri.org/IRoomInfoManagement/UpdateRoomInfoResponse")]
        System.Threading.Tasks.Task<int> UpdateRoomInfoAsync(KtvStudio.RoomInfoService.RoomInfo roomInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/GetActionSource", ReplyAction="http://tempuri.org/IRoomInfoManagement/GetActionSourceResponse")]
        System.Data.DataTable GetActionSource(string groupCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomInfoManagement/GetActionSource", ReplyAction="http://tempuri.org/IRoomInfoManagement/GetActionSourceResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetActionSourceAsync(string groupCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomInfoManagementChannel : KtvStudio.RoomInfoService.IRoomInfoManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomInfoManagementClient : System.ServiceModel.ClientBase<KtvStudio.RoomInfoService.IRoomInfoManagement>, KtvStudio.RoomInfoService.IRoomInfoManagement {
        
        public RoomInfoManagementClient() {
        }
        
        public RoomInfoManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomInfoManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomInfoManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomInfoManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllRoomInfo() {
            return base.Channel.GetAllRoomInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllRoomInfoAsync() {
            return base.Channel.GetAllRoomInfoAsync();
        }
        
        public int InsertRoomInfo(KtvStudio.RoomInfoService.RoomInfo roomInfo) {
            return base.Channel.InsertRoomInfo(roomInfo);
        }
        
        public System.Threading.Tasks.Task<int> InsertRoomInfoAsync(KtvStudio.RoomInfoService.RoomInfo roomInfo) {
            return base.Channel.InsertRoomInfoAsync(roomInfo);
        }
        
        public int RemoveRoomInfo(string roomId) {
            return base.Channel.RemoveRoomInfo(roomId);
        }
        
        public System.Threading.Tasks.Task<int> RemoveRoomInfoAsync(string roomId) {
            return base.Channel.RemoveRoomInfoAsync(roomId);
        }
        
        public int UpdateRoomInfo(KtvStudio.RoomInfoService.RoomInfo roomInfo) {
            return base.Channel.UpdateRoomInfo(roomInfo);
        }
        
        public System.Threading.Tasks.Task<int> UpdateRoomInfoAsync(KtvStudio.RoomInfoService.RoomInfo roomInfo) {
            return base.Channel.UpdateRoomInfoAsync(roomInfo);
        }
        
        public System.Data.DataTable GetActionSource(string groupCode) {
            return base.Channel.GetActionSource(groupCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetActionSourceAsync(string groupCode) {
            return base.Channel.GetActionSourceAsync(groupCode);
        }
    }
}
