# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI branch
-
  branches:
    only:
      - develop

  version: 6.0.0-dev{build}
  configuration: Release

  init:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version.Replace("-dev$env:appveyor_build_number", "-dev"))$($env:appveyor_build_number.PadLeft(4, '0'))"

  # Install scripts. (runs after repo cloning)
  install:
    - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

  build_script:
    - msbuild Fluent.Ribbon.msbuild /target:CI /v:m /nologo

  after_build:
    - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

  artifacts:
    - path: Publish\**\*.nupkg
      name: NuGet
  
    - path: Publish\**\*.zip
      name: zip

  assembly_info:
    patch: true
    file: Shared\GlobalAssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/855da764a995f5aa1a24
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: false

# configuration for master/CI branch
-
  branches:
    only:
      - master

  version: 5.0.1.{build}
  configuration: Release

  # Install scripts. (runs after repo cloning)
  install:
    - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

  build_script:
    - msbuild Fluent.Ribbon.msbuild /target:CI /v:m /nologo

  after_build:
    - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

  artifacts:
    - path: Publish\**\*.nupkg
      name: NuGet
  
    - path: Publish\**\*.zip
      name: zip

  assembly_info:
    patch: true
    file: Shared\GlobalAssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/855da764a995f5aa1a24
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: false