//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KtvMusic.SongInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SongInfo", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class SongInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MVUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MusicNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MusicNameInitialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NewSongHotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingRailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SingerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageType {
            get {
                return this.LanguageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageTypeField, value) != true)) {
                    this.LanguageTypeField = value;
                    this.RaisePropertyChanged("LanguageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MVUrl {
            get {
                return this.MVUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.MVUrlField, value) != true)) {
                    this.MVUrlField = value;
                    this.RaisePropertyChanged("MVUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MusicName {
            get {
                return this.MusicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MusicNameField, value) != true)) {
                    this.MusicNameField = value;
                    this.RaisePropertyChanged("MusicName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MusicNameInitials {
            get {
                return this.MusicNameInitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.MusicNameInitialsField, value) != true)) {
                    this.MusicNameInitialsField = value;
                    this.RaisePropertyChanged("MusicNameInitials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NewSongHot {
            get {
                return this.NewSongHotField;
            }
            set {
                if ((this.NewSongHotField.Equals(value) != true)) {
                    this.NewSongHotField = value;
                    this.RaisePropertyChanged("NewSongHot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingRail {
            get {
                return this.SingRailField;
            }
            set {
                if ((object.ReferenceEquals(this.SingRailField, value) != true)) {
                    this.SingRailField = value;
                    this.RaisePropertyChanged("SingRail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SingerId {
            get {
                return this.SingerIdField;
            }
            set {
                if ((this.SingerIdField.Equals(value) != true)) {
                    this.SingerIdField = value;
                    this.RaisePropertyChanged("SingerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerName {
            get {
                return this.SingerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerNameField, value) != true)) {
                    this.SingerNameField = value;
                    this.RaisePropertyChanged("SingerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SongRecord", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class SongRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClickNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SongIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClickNum {
            get {
                return this.ClickNumField;
            }
            set {
                if ((this.ClickNumField.Equals(value) != true)) {
                    this.ClickNumField = value;
                    this.RaisePropertyChanged("ClickNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SongId {
            get {
                return this.SongIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SongIdField, value) != true)) {
                    this.SongIdField = value;
                    this.RaisePropertyChanged("SongId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SongInfoService.ISongInfoManagement")]
    public interface ISongInfoManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetAllSongInfo", ReplyAction="http://tempuri.org/ISongInfoManagement/GetAllSongInfoResponse")]
        System.Data.DataTable GetAllSongInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetAllSongInfo", ReplyAction="http://tempuri.org/ISongInfoManagement/GetAllSongInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllSongInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/AddSongInfo", ReplyAction="http://tempuri.org/ISongInfoManagement/AddSongInfoResponse")]
        int AddSongInfo(KtvMusic.SongInfoService.SongInfo songInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/AddSongInfo", ReplyAction="http://tempuri.org/ISongInfoManagement/AddSongInfoResponse")]
        System.Threading.Tasks.Task<int> AddSongInfoAsync(KtvMusic.SongInfoService.SongInfo songInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/UpdateSongeInfo", ReplyAction="http://tempuri.org/ISongInfoManagement/UpdateSongeInfoResponse")]
        int UpdateSongeInfo(KtvMusic.SongInfoService.SongInfo songInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/UpdateSongeInfo", ReplyAction="http://tempuri.org/ISongInfoManagement/UpdateSongeInfoResponse")]
        System.Threading.Tasks.Task<int> UpdateSongeInfoAsync(KtvMusic.SongInfoService.SongInfo songInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/DeleteSongInfo", ReplyAction="http://tempuri.org/ISongInfoManagement/DeleteSongInfoResponse")]
        int DeleteSongInfo(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/DeleteSongInfo", ReplyAction="http://tempuri.org/ISongInfoManagement/DeleteSongInfoResponse")]
        System.Threading.Tasks.Task<int> DeleteSongInfoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetSongInfoBySingerId", ReplyAction="http://tempuri.org/ISongInfoManagement/GetSongInfoBySingerIdResponse")]
        System.Data.DataTable GetSongInfoBySingerId(string singerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetSongInfoBySingerId", ReplyAction="http://tempuri.org/ISongInfoManagement/GetSongInfoBySingerIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSongInfoBySingerIdAsync(string singerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetAllCategorySource", ReplyAction="http://tempuri.org/ISongInfoManagement/GetAllCategorySourceResponse")]
        System.Data.DataTable GetAllCategorySource();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetAllCategorySource", ReplyAction="http://tempuri.org/ISongInfoManagement/GetAllCategorySourceResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllCategorySourceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetCategorySourceByFatherId", ReplyAction="http://tempuri.org/ISongInfoManagement/GetCategorySourceByFatherIdResponse")]
        System.Data.DataTable GetCategorySourceByFatherId(string fatherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetCategorySourceByFatherId", ReplyAction="http://tempuri.org/ISongInfoManagement/GetCategorySourceByFatherIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCategorySourceByFatherIdAsync(string fatherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/AddSongRecord", ReplyAction="http://tempuri.org/ISongInfoManagement/AddSongRecordResponse")]
        int AddSongRecord(KtvMusic.SongInfoService.SongRecord[] records);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/AddSongRecord", ReplyAction="http://tempuri.org/ISongInfoManagement/AddSongRecordResponse")]
        System.Threading.Tasks.Task<int> AddSongRecordAsync(KtvMusic.SongInfoService.SongRecord[] records);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetAllSongRecord", ReplyAction="http://tempuri.org/ISongInfoManagement/GetAllSongRecordResponse")]
        System.Data.DataTable GetAllSongRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/GetAllSongRecord", ReplyAction="http://tempuri.org/ISongInfoManagement/GetAllSongRecordResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllSongRecordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/UpdateNewSongRank", ReplyAction="http://tempuri.org/ISongInfoManagement/UpdateNewSongRankResponse")]
        int UpdateNewSongRank(System.Collections.Generic.Dictionary<string, double> newRank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongInfoManagement/UpdateNewSongRank", ReplyAction="http://tempuri.org/ISongInfoManagement/UpdateNewSongRankResponse")]
        System.Threading.Tasks.Task<int> UpdateNewSongRankAsync(System.Collections.Generic.Dictionary<string, double> newRank);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISongInfoManagementChannel : KtvMusic.SongInfoService.ISongInfoManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SongInfoManagementClient : System.ServiceModel.ClientBase<KtvMusic.SongInfoService.ISongInfoManagement>, KtvMusic.SongInfoService.ISongInfoManagement {
        
        public SongInfoManagementClient() {
        }
        
        public SongInfoManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SongInfoManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SongInfoManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SongInfoManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllSongInfo() {
            return base.Channel.GetAllSongInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllSongInfoAsync() {
            return base.Channel.GetAllSongInfoAsync();
        }
        
        public int AddSongInfo(KtvMusic.SongInfoService.SongInfo songInfo) {
            return base.Channel.AddSongInfo(songInfo);
        }
        
        public System.Threading.Tasks.Task<int> AddSongInfoAsync(KtvMusic.SongInfoService.SongInfo songInfo) {
            return base.Channel.AddSongInfoAsync(songInfo);
        }
        
        public int UpdateSongeInfo(KtvMusic.SongInfoService.SongInfo songInfo) {
            return base.Channel.UpdateSongeInfo(songInfo);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSongeInfoAsync(KtvMusic.SongInfoService.SongInfo songInfo) {
            return base.Channel.UpdateSongeInfoAsync(songInfo);
        }
        
        public int DeleteSongInfo(string id) {
            return base.Channel.DeleteSongInfo(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteSongInfoAsync(string id) {
            return base.Channel.DeleteSongInfoAsync(id);
        }
        
        public System.Data.DataTable GetSongInfoBySingerId(string singerId) {
            return base.Channel.GetSongInfoBySingerId(singerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSongInfoBySingerIdAsync(string singerId) {
            return base.Channel.GetSongInfoBySingerIdAsync(singerId);
        }
        
        public System.Data.DataTable GetAllCategorySource() {
            return base.Channel.GetAllCategorySource();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllCategorySourceAsync() {
            return base.Channel.GetAllCategorySourceAsync();
        }
        
        public System.Data.DataTable GetCategorySourceByFatherId(string fatherId) {
            return base.Channel.GetCategorySourceByFatherId(fatherId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCategorySourceByFatherIdAsync(string fatherId) {
            return base.Channel.GetCategorySourceByFatherIdAsync(fatherId);
        }
        
        public int AddSongRecord(KtvMusic.SongInfoService.SongRecord[] records) {
            return base.Channel.AddSongRecord(records);
        }
        
        public System.Threading.Tasks.Task<int> AddSongRecordAsync(KtvMusic.SongInfoService.SongRecord[] records) {
            return base.Channel.AddSongRecordAsync(records);
        }
        
        public System.Data.DataTable GetAllSongRecord() {
            return base.Channel.GetAllSongRecord();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllSongRecordAsync() {
            return base.Channel.GetAllSongRecordAsync();
        }
        
        public int UpdateNewSongRank(System.Collections.Generic.Dictionary<string, double> newRank) {
            return base.Channel.UpdateNewSongRank(newRank);
        }
        
        public System.Threading.Tasks.Task<int> UpdateNewSongRankAsync(System.Collections.Generic.Dictionary<string, double> newRank) {
            return base.Channel.UpdateNewSongRankAsync(newRank);
        }
    }
}
