//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KtvStudio.SingerInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingerInfo", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class SingerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerClickNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerEnglishNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerInitialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerIntroduceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerNationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerOtherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerPhotoUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingerSexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerClickNum {
            get {
                return this.SingerClickNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerClickNumField, value) != true)) {
                    this.SingerClickNumField = value;
                    this.RaisePropertyChanged("SingerClickNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerEnglishName {
            get {
                return this.SingerEnglishNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerEnglishNameField, value) != true)) {
                    this.SingerEnglishNameField = value;
                    this.RaisePropertyChanged("SingerEnglishName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerInitials {
            get {
                return this.SingerInitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerInitialsField, value) != true)) {
                    this.SingerInitialsField = value;
                    this.RaisePropertyChanged("SingerInitials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerIntroduce {
            get {
                return this.SingerIntroduceField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerIntroduceField, value) != true)) {
                    this.SingerIntroduceField = value;
                    this.RaisePropertyChanged("SingerIntroduce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerName {
            get {
                return this.SingerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerNameField, value) != true)) {
                    this.SingerNameField = value;
                    this.RaisePropertyChanged("SingerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerNationality {
            get {
                return this.SingerNationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerNationalityField, value) != true)) {
                    this.SingerNationalityField = value;
                    this.RaisePropertyChanged("SingerNationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerOtherName {
            get {
                return this.SingerOtherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerOtherNameField, value) != true)) {
                    this.SingerOtherNameField = value;
                    this.RaisePropertyChanged("SingerOtherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerPhotoUrl {
            get {
                return this.SingerPhotoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerPhotoUrlField, value) != true)) {
                    this.SingerPhotoUrlField = value;
                    this.RaisePropertyChanged("SingerPhotoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingerSex {
            get {
                return this.SingerSexField;
            }
            set {
                if ((object.ReferenceEquals(this.SingerSexField, value) != true)) {
                    this.SingerSexField = value;
                    this.RaisePropertyChanged("SingerSex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SingerInfoService.ISingerInfoManagement")]
    public interface ISingerInfoManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetAllSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetAllSingerInfoResponse")]
        System.Data.DataTable GetAllSingerInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetAllSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetAllSingerInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllSingerInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/AddSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/AddSingerInfoResponse")]
        int AddSingerInfo(KtvStudio.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/AddSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/AddSingerInfoResponse")]
        System.Threading.Tasks.Task<int> AddSingerInfoAsync(KtvStudio.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/UpdateSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/UpdateSingerInfoResponse")]
        int UpdateSingerInfo(KtvStudio.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/UpdateSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/UpdateSingerInfoResponse")]
        System.Threading.Tasks.Task<int> UpdateSingerInfoAsync(KtvStudio.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/DeleteSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/DeleteSingerInfoResponse")]
        int DeleteSingerInfo(KtvStudio.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/DeleteSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/DeleteSingerInfoResponse")]
        System.Threading.Tasks.Task<int> DeleteSingerInfoAsync(KtvStudio.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByName", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByNameResponse")]
        System.Data.DataTable GetSingerInfoByName(string singerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByName", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByNameResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSingerInfoByNameAsync(string singerName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISingerInfoManagementChannel : KtvStudio.SingerInfoService.ISingerInfoManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingerInfoManagementClient : System.ServiceModel.ClientBase<KtvStudio.SingerInfoService.ISingerInfoManagement>, KtvStudio.SingerInfoService.ISingerInfoManagement {
        
        public SingerInfoManagementClient() {
        }
        
        public SingerInfoManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingerInfoManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingerInfoManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingerInfoManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllSingerInfo() {
            return base.Channel.GetAllSingerInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllSingerInfoAsync() {
            return base.Channel.GetAllSingerInfoAsync();
        }
        
        public int AddSingerInfo(KtvStudio.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.AddSingerInfo(singerInfo);
        }
        
        public System.Threading.Tasks.Task<int> AddSingerInfoAsync(KtvStudio.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.AddSingerInfoAsync(singerInfo);
        }
        
        public int UpdateSingerInfo(KtvStudio.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.UpdateSingerInfo(singerInfo);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSingerInfoAsync(KtvStudio.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.UpdateSingerInfoAsync(singerInfo);
        }
        
        public int DeleteSingerInfo(KtvStudio.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.DeleteSingerInfo(singerInfo);
        }
        
        public System.Threading.Tasks.Task<int> DeleteSingerInfoAsync(KtvStudio.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.DeleteSingerInfoAsync(singerInfo);
        }
        
        public System.Data.DataTable GetSingerInfoByName(string singerName) {
            return base.Channel.GetSingerInfoByName(singerName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSingerInfoByNameAsync(string singerName) {
            return base.Channel.GetSingerInfoByNameAsync(singerName);
        }
    }
}
