//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KtvStudio.SingerInfoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SingerInfoService.ISingerInfoManagement")]
    public interface ISingerInfoManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetAllSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetAllSingerInfoResponse")]
        System.Data.DataTable GetAllSingerInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetAllSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetAllSingerInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllSingerInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetSingerInfoPaging", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetSingerInfoPagingResponse")]
        System.Data.DataTable GetSingerInfoPaging(string nationality, string sex, string initial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetSingerInfoPaging", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetSingerInfoPagingResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSingerInfoPagingAsync(string nationality, string sex, string initial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/AddSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/AddSingerInfoResponse")]
        int AddSingerInfo(KtvMusic.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/AddSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/AddSingerInfoResponse")]
        System.Threading.Tasks.Task<int> AddSingerInfoAsync(KtvMusic.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/UpdateSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/UpdateSingerInfoResponse")]
        int UpdateSingerInfo(KtvMusic.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/UpdateSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/UpdateSingerInfoResponse")]
        System.Threading.Tasks.Task<int> UpdateSingerInfoAsync(KtvMusic.SingerInfoService.SingerInfo singerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/DeleteSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/DeleteSingerInfoResponse")]
        int DeleteSingerInfo(string singerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/DeleteSingerInfo", ReplyAction="http://tempuri.org/ISingerInfoManagement/DeleteSingerInfoResponse")]
        System.Threading.Tasks.Task<int> DeleteSingerInfoAsync(string singerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByName", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByNameResponse")]
        System.Data.DataTable GetSingerInfoByName(string singerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByName", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByNameResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSingerInfoByNameAsync(string singerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetSingerInfoById", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByIdResponse")]
        KtvMusic.SingerInfoService.SingerInfo GetSingerInfoById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetSingerInfoById", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetSingerInfoByIdResponse")]
        System.Threading.Tasks.Task<KtvMusic.SingerInfoService.SingerInfo> GetSingerInfoByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetNationalityInfoSource", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetNationalityInfoSourceResponse")]
        System.Data.DataTable GetNationalityInfoSource();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/GetNationalityInfoSource", ReplyAction="http://tempuri.org/ISingerInfoManagement/GetNationalityInfoSourceResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNationalityInfoSourceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/UpdateNewSingerRank", ReplyAction="http://tempuri.org/ISingerInfoManagement/UpdateNewSingerRankResponse")]
        int UpdateNewSingerRank(System.Collections.Generic.Dictionary<string, int> singerClickNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingerInfoManagement/UpdateNewSingerRank", ReplyAction="http://tempuri.org/ISingerInfoManagement/UpdateNewSingerRankResponse")]
        System.Threading.Tasks.Task<int> UpdateNewSingerRankAsync(System.Collections.Generic.Dictionary<string, int> singerClickNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISingerInfoManagementChannel : KtvStudio.SingerInfoService.ISingerInfoManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingerInfoManagementClient : System.ServiceModel.ClientBase<KtvStudio.SingerInfoService.ISingerInfoManagement>, KtvStudio.SingerInfoService.ISingerInfoManagement {
        
        public SingerInfoManagementClient() {
        }
        
        public SingerInfoManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingerInfoManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingerInfoManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingerInfoManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllSingerInfo() {
            return base.Channel.GetAllSingerInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllSingerInfoAsync() {
            return base.Channel.GetAllSingerInfoAsync();
        }
        
        public System.Data.DataTable GetSingerInfoPaging(string nationality, string sex, string initial) {
            return base.Channel.GetSingerInfoPaging(nationality, sex, initial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSingerInfoPagingAsync(string nationality, string sex, string initial) {
            return base.Channel.GetSingerInfoPagingAsync(nationality, sex, initial);
        }
        
        public int AddSingerInfo(KtvMusic.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.AddSingerInfo(singerInfo);
        }
        
        public System.Threading.Tasks.Task<int> AddSingerInfoAsync(KtvMusic.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.AddSingerInfoAsync(singerInfo);
        }
        
        public int UpdateSingerInfo(KtvMusic.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.UpdateSingerInfo(singerInfo);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSingerInfoAsync(KtvMusic.SingerInfoService.SingerInfo singerInfo) {
            return base.Channel.UpdateSingerInfoAsync(singerInfo);
        }
        
        public int DeleteSingerInfo(string singerId) {
            return base.Channel.DeleteSingerInfo(singerId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteSingerInfoAsync(string singerId) {
            return base.Channel.DeleteSingerInfoAsync(singerId);
        }
        
        public System.Data.DataTable GetSingerInfoByName(string singerName) {
            return base.Channel.GetSingerInfoByName(singerName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSingerInfoByNameAsync(string singerName) {
            return base.Channel.GetSingerInfoByNameAsync(singerName);
        }
        
        public KtvMusic.SingerInfoService.SingerInfo GetSingerInfoById(string id) {
            return base.Channel.GetSingerInfoById(id);
        }
        
        public System.Threading.Tasks.Task<KtvMusic.SingerInfoService.SingerInfo> GetSingerInfoByIdAsync(string id) {
            return base.Channel.GetSingerInfoByIdAsync(id);
        }
        
        public System.Data.DataTable GetNationalityInfoSource() {
            return base.Channel.GetNationalityInfoSource();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNationalityInfoSourceAsync() {
            return base.Channel.GetNationalityInfoSourceAsync();
        }
        
        public int UpdateNewSingerRank(System.Collections.Generic.Dictionary<string, int> singerClickNum) {
            return base.Channel.UpdateNewSingerRank(singerClickNum);
        }
        
        public System.Threading.Tasks.Task<int> UpdateNewSingerRankAsync(System.Collections.Generic.Dictionary<string, int> singerClickNum) {
            return base.Channel.UpdateNewSingerRankAsync(singerClickNum);
        }
    }
}
